from chinatravel.agent.nesy_agent.prompts.prompts import (
    NEXT_POI_TYPE_INSTRUCTION,
    INTERCITY_TRANSPORT_GO_INSTRUCTION,
    INTERCITY_TRANSPORT_BACK_INSTRUCTION,
    HOTEL_RANKING_INSTRUCTION,
    ATTRACTION_RANKING_INSTRUCTION,
    RESTAURANT_RANKING_INSTRUCTION,
    SELECT_POI_TIME_INSTRUCTION,
    ROOMS_PLANNING_INSTRUCTION, 
    INNERCITY_TRANSPORTS_SELECTION_INSTRUCTION, 
    BUDGETS_INSTRUCTION, 
    NL2SL_INSTRUCTION,
    NL2SL_INSTRUCTION_V2,
)

__all__ = [
    "NEXT_POI_TYPE_INSTRUCTION",
    "INTERCITY_TRANSPORT_GO_INSTRUCTION",
    "INTERCITY_TRANSPORT_BACK_INSTRUCTION",
    "HOTEL_RANKING_INSTRUCTION",
    "ATTRACTION_RANKING_INSTRUCTION",
    "RESTAURANT_RANKING_INSTRUCTION",
    "SELECT_POI_TIME_INSTRUCTION",
    "ROOMS_PLANNING_INSTRUCTION", 
    "INNERCITY_TRANSPORTS_SELECTION_INSTRUCTION", 
    "NL2SL_INSTRUCTION",
    "NL2SL_INSTRUCTION_V2", 
    "BUDGETS_INSTRUCTION", 
]
